// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using v00v.Services.Database;

namespace v00v.Services.Database.Migrations
{
    [DbContext(typeof(VideoContext))]
    [Migration("20191002091422_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("v00v.Services.Database.Models.AppLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("AppStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now','localtime')");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemsCount")
                        .HasColumnType("INTEGER");
                        
                    b.Property<long>("PlannedCount")
                        .HasColumnType("INTEGER");
                        
                    b.Property<int>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<long>("SubsCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubsCountDiff")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Sync")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<long>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ViewCountDiff")
                        .HasColumnType("INTEGER");
                        
                    b.Property<long>("WatchedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("v00v.Services.Database.Models.ChannelTag", b =>
                {
                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChannelId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ChannelTags");
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Comments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("DislikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<long>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<long>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ViewDiff")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("WatchState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("v00v.Services.Database.Models.ItemPlaylist", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlaylistId")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.ToTable("ItemPlaylists");
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<byte>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cookie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pass")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "youtube.com"
                        });
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "авто"
                        },
                        new
                        {
                            Id = 2,
                            Text = "музыка"
                        },
                        new
                        {
                            Id = 3,
                            Text = "смешное"
                        },
                        new
                        {
                            Id = 4,
                            Text = "мото"
                        },
                        new
                        {
                            Id = 5,
                            Text = "наука"
                        },
                        new
                        {
                            Id = 6,
                            Text = "новости"
                        },
                        new
                        {
                            Id = 7,
                            Text = "еда"
                        },
                        new
                        {
                            Id = 8,
                            Text = "техника"
                        },
                        new
                        {
                            Id = 9,
                            Text = "танцы"
                        },
                        new
                        {
                            Id = 10,
                            Text = "вело"
                        },
                        new
                        {
                            Id = 11,
                            Text = "природа"
                        },
                        new
                        {
                            Id = 12,
                            Text = "интервью"
                        },
                        new
                        {
                            Id = 13,
                            Text = "ревью"
                        },
                        new
                        {
                            Id = 14,
                            Text = "религия"
                        },
                        new
                        {
                            Id = 15,
                            Text = "diy"
                        },
                        new
                        {
                            Id = 16,
                            Text = "ремонт"
                        },
                        new
                        {
                            Id = 17,
                            Text = "история"
                        },
                        new
                        {
                            Id = 18,
                            Text = "обучение"
                        },
                        new
                        {
                            Id = 19,
                            Text = "игры"
                        },
                        new
                        {
                            Id = 20,
                            Text = "путешествия"
                        },
                        new
                        {
                            Id = 21,
                            Text = "тренировки"
                        },
                        new
                        {
                            Id = 22,
                            Text = "дубна"
                        },
                        new
                        {
                            Id = 23,
                            Text = "сплав"
                        },
                        new
                        {
                            Id = 24,
                            Text = "политика"
                        },
                        new
                        {
                            Id = 25,
                            Text = "эмиграция"
                        },
                        new
                        {
                            Id = 26,
                            Text = "оффроад"
                        },
                        new
                        {
                            Id = 27,
                            Text = "мультики"
                        },
                        new
                        {
                            Id = 28,
                            Text = "электротранспорт"
                        });
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Channel", b =>
                {
                    b.HasOne("v00v.Services.Database.Models.Site", "Site")
                        .WithMany("Channels")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("v00v.Services.Database.Models.ChannelTag", b =>
                {
                    b.HasOne("v00v.Services.Database.Models.Channel", null)
                        .WithMany("Tags")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("v00v.Services.Database.Models.Tag", null)
                        .WithMany("Channels")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Item", b =>
                {
                    b.HasOne("v00v.Services.Database.Models.Channel", "Channel")
                        .WithMany("Items")
                        .HasForeignKey("ChannelId");
                });

            modelBuilder.Entity("v00v.Services.Database.Models.ItemPlaylist", b =>
                {
                    b.HasOne("v00v.Services.Database.Models.Item", null)
                        .WithMany("Playlists")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("v00v.Services.Database.Models.Playlist", null)
                        .WithMany("Items")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("v00v.Services.Database.Models.Playlist", b =>
                {
                    b.HasOne("v00v.Services.Database.Models.Channel", "Channel")
                        .WithMany("Playlists")
                        .HasForeignKey("ChannelId");
                });
#pragma warning restore 612, 618
        }
    }
}
